#! /usr/bin/env bash

shopt -s extglob
set -o pipefail   # trace error through pipes
set -o errtrace   # trace error through time command
#set -o xtrace     # trace commands before they are executed
#set -o nounset    # exit if any used var was not initialized
#set -o errexit    # exit if any statement returns an error
set +o noclobber

INCANTATIONS_ROOT="$(dirname "$(readlink -f "$0")")"

[[ -f .env ]] && source .env

if [[ ! -d $INCANTATIONS_ROOT ]]; then
  echo -e "\033[0;31mFatal Error: This script could not find where the spells are located, Error: 1\033[0m]" >&2
  exit 1
fi
source $INCANTATIONS_ROOT/toolbox

command -v git    &>/dev/null || die "You need git (please check https://git-scm.com)" -1

function gpA() { # {{{
  local folder="$1"
  local remotes=( $(git -C "$folder" remote -v | grep push | cut -f1) )
  local current_branch=$(git -C "$folder" branch --show-current)

  verbose "  Pushing to ${#remotes[@]} remotes"
  for remote in ${remotes[@]}; do
    if [[ -n $(git -C "$folder" remote -v | grep $remote | head -1 | grep -i genesyscsp) ]]; then
      # This remote is used by Appveyor to start builds
      # We should push master by itself
      master=$(git -C $folder branch --sort=-refname | grep -Eo -m1 '(main|master|production|dev)')
      verbose "  Pushing $master to $remote"
      if [[ $current_branch != $master ]]; then
        dry_run git -C "$folder" checkout    $master
        dry_run git -C "$folder" push origin $master
        dry_run git -C "$folder" checkout    $current_branch
      else
        dry_run git -C "$folder" push origin $master
      fi
    fi
    verbose "  Pushing to $remote"
    dry_run git -C "$folder" push --all $remote
    verbose "  Pushing tags to $remote"
    dry_run git -C "$folder" push --tags $remote
  done
} # }}}

function main() { # {{{
  parse_args "" "$@"

  for folder in *; do
    [[ ! -d $folder ]]            && continue
    [[ ! -d $folder/.git ]]       && continue
    [[ $folder =~ .*-EOL$ ]]      && continue
    [[ $folder =~ .*-IGNORE$ ]]   && continue
    [[ $folder =~ .*-NOTREADY$ ]] && continue
    title "Processing $folder"
    gpA "$folder"
  done
} # }}}

main "$@"
